CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--;;

CREATE TABLE IF NOT EXISTS ATTENDING (
  id uuid UNIQUE NOT NULL PRIMARY KEY,
  removed BOOLEAN DEFAULT FALSE,
  students_id uuid NOT NULL FOREIGN KEY REFERENCES students(id),
  subjects_id uuid NOT NULL FOREIGN KEY REFERENCES subjects(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
