CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--;;

CREATE TABLE IF NOT EXISTS STUDENTS (
  id uuid UNIQUE NOT NULL PRIMARY KEY,
  removed BOOLEAN DEFAULT FALSE,
  name VARCHAR(255) NOT NULL,
  document VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  birthdate DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
