CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--;;

CREATE TABLE IF NOT EXISTS ATTENDING (
  id uuid UNIQUE NOT NULL PRIMARY KEY,
  removed BOOLEAN DEFAULT FALSE,
  students_id uuid NOT NULL,
  subjects_id uuid NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_students FOREIGN KEY (students_id) REFERENCES students(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_subjects FOREIGN KEY (subjects_id) REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE CASCADE
);
